-- Supabase / PostgreSQL schema draft for BEC Equipment Management
-- Generated from current MySQL app structure and backup references.
-- Goal: preserve compatibility first, then normalize later.

begin;

create extension if not exists pgcrypto;

-- =========================================================
-- Helpers
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================================================
-- Core reference tables
-- =========================================================

create table if not exists public.categories (
  category_id integer generated by default as identity primary key,
  category_name varchar(100) not null unique,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_categories_name on public.categories (category_name);

create table if not exists public.users (
  user_id varchar(32) primary key,
  username varchar(50) not null unique,
  password varchar(255) not null,
  fullname varchar(100) not null,
  email varchar(150) not null unique,
  phone varchar(20),
  department varchar(100),
  role text not null check (role in ('admin','pmo','dean','finance','technician','reporter','student','faculty','handler','guest')),
  status text not null default 'active' check (status in ('active','inactive','suspended')),
  created_at timestamptz not null default now(),
  last_login timestamptz
);

create index if not exists idx_users_email on public.users (email);
create index if not exists idx_users_role on public.users (role);
create index if not exists idx_users_status on public.users (status);

create table if not exists public.equipment (
  equipment_id varchar(32) primary key,
  asset_tag varchar(50) not null unique,
  equipment_name varchar(200) not null,
  category_id integer references public.categories(category_id) on delete set null,
  category text,
  equipment_category text,
  description text,
  location varchar(200),
  department varchar(120),
  status text not null default 'available' check (status in ('available','reserved','in_use','in-use','maintenance','under_maintenance','defective','faulty','retired','deleted')),
  condition_status text default 'good' check (condition_status in ('excellent','good','fair','poor','damaged')),
  condition text,
  purchase_date date,
  purchase_cost numeric(10,2),
  warranty_expiry date,
  quantity integer not null default 1,
  min_stock_level integer not null default 1,
  reorder_point integer not null default 0,
  supplier_info text,
  photo text,
  brand varchar(120),
  model varchar(120),
  counted integer,
  remarks text,
  notes text,
  acquired date,
  issued date,
  last_inventory_check timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_equipment_status on public.equipment (status);
create index if not exists idx_equipment_category_id on public.equipment (category_id);
create index if not exists idx_equipment_name on public.equipment (equipment_name);

drop trigger if exists trg_equipment_updated_at on public.equipment;

create trigger trg_equipment_updated_at
before update on public.equipment
for each row execute function public.set_updated_at();

-- =========================================================
-- Compatibility role tables still referenced by app code
-- =========================================================

create table if not exists public.admins (
  admin_id varchar(32) primary key,
  username varchar(50) not null unique,
  password varchar(255) not null,
  fullname varchar(100) not null,
  email varchar(150) not null unique,
  phone varchar(20),
  status text not null default 'active' check (status in ('active','inactive','suspended')),
  created_at timestamptz not null default now(),
  last_login timestamptz
);

create table if not exists public.students (
  student_id varchar(32) primary key,
  username varchar(50) not null unique,
  password varchar(255) not null,
  fullname varchar(100) not null,
  email varchar(150) not null unique,
  phone varchar(20),
  student_number varchar(50),
  course varchar(150),
  status text not null default 'active' check (status in ('active','inactive','suspended')),
  created_at timestamptz not null default now(),
  last_login timestamptz
);

create table if not exists public.faculty_members (
  faculty_id varchar(32) primary key,
  username varchar(50) not null unique,
  password varchar(255) not null,
  fullname varchar(100) not null,
  email varchar(150) not null unique,
  phone varchar(20),
  department varchar(100),
  status text not null default 'active' check (status in ('active','inactive','suspended')),
  created_at timestamptz not null default now(),
  last_login timestamptz
);

create table if not exists public.maintenance_technicians (
  technician_id varchar(32) primary key,
  username varchar(50) not null unique,
  password varchar(255) not null,
  fullname varchar(100) not null,
  email varchar(150) not null unique,
  phone varchar(20),
  specialization varchar(120),
  department varchar(100),
  status text not null default 'active' check (status in ('active','inactive','suspended')),
  created_at timestamptz not null default now(),
  last_login timestamptz
);

-- =========================================================
-- Defect workflow
-- =========================================================

create table if not exists public.defect_reports (
  report_id varchar(32) primary key,
  equipment_id varchar(32) not null references public.equipment(equipment_id) on delete restrict,
  reported_by varchar(32),
  issue_description text,
  defect_description text,
  priority text not null default 'medium' check (priority in ('critical','high','medium','low')),
  status text not null default 'reported' check (
    status in (
      'reported','pmo_review','dean_review','finance_review','on_hold_budget','ready_for_assignment',
      'assigned','in_progress','for_replacement','completed','verified','closed','rejected'
    )
  ),
  assigned_to varchar(32),
  assigned_technician varchar(32),
  assigned_by varchar(32),
  department_assigned varchar(120),
  handler_instructions text,
  instructions text,
  category varchar(120),
  location varchar(200),
  equipment_name varchar(200),
  work_order_id varchar(32),
  photo_path text,
  photo_url text,
  image_path text,
  defect_photos jsonb,
  technician_notes text,
  resolution_notes text,
  verification_notes text,
  notes text,
  assigned_date timestamptz,
  started_at timestamptz,
  completion_date timestamptz,
  report_date timestamptz not null default now()
);

create index if not exists idx_defect_reports_equipment_id on public.defect_reports (equipment_id);
create index if not exists idx_defect_reports_reported_by on public.defect_reports (reported_by);
create index if not exists idx_defect_reports_assigned_to on public.defect_reports (assigned_to);
create index if not exists idx_defect_reports_status on public.defect_reports (status);
create index if not exists idx_defect_reports_priority on public.defect_reports (priority);
create index if not exists idx_defect_reports_report_date on public.defect_reports (report_date desc);

create table if not exists public.work_orders (
  work_order_id varchar(32) primary key,
  report_id varchar(32) references public.defect_reports(report_id) on delete set null,
  title varchar(255) not null,
  department varchar(120),
  priority text not null default 'medium' check (priority in ('critical','high','medium','low')),
  due_date date,
  assigned_technician varchar(32),
  notes text,
  completion_note text,
  status text not null default 'open' check (status in ('open','in_progress','completed','closed','on_hold','deleted')),
  created_by varchar(32),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_work_orders_report_id on public.work_orders (report_id);
create index if not exists idx_work_orders_status on public.work_orders (status);
create index if not exists idx_work_orders_priority on public.work_orders (priority);
create index if not exists idx_work_orders_due_date on public.work_orders (due_date);

drop trigger if exists trg_work_orders_updated_at on public.work_orders;

create trigger trg_work_orders_updated_at
before update on public.work_orders
for each row execute function public.set_updated_at();

-- =========================================================
-- Reservations
-- =========================================================

create table if not exists public.reservations (
  reservation_id varchar(32) primary key,
  equipment_id varchar(32) not null references public.equipment(equipment_id) on delete restrict,
  user_id varchar(32) not null,
  request_date timestamptz not null default now(),
  start_date timestamptz not null,
  end_date timestamptz not null,
  purpose text,
  status text not null default 'pending' check (status in ('pending','approved','active','completed','rejected','cancelled')),
  approved_by varchar(32),
  approval_date timestamptz,
  notes text
);

create index if not exists idx_reservations_user_id on public.reservations (user_id);
create index if not exists idx_reservations_status on public.reservations (status);
create index if not exists idx_reservations_start_date on public.reservations (start_date);
create index if not exists idx_reservations_end_date on public.reservations (end_date);

-- =========================================================
-- Notifications and auth support tables
-- =========================================================

create table if not exists public.notifications (
  notification_id varchar(50) primary key,
  user_id varchar(32),
  sender_id varchar(32),
  message text not null,
  type varchar(50) not null,
  link text,
  related_id varchar(50),
  is_read boolean not null default false,
  read_at timestamptz,
  created_date timestamptz not null default now()
);

create index if not exists idx_notifications_user_id on public.notifications (user_id);
create index if not exists idx_notifications_type on public.notifications (type);
create index if not exists idx_notifications_created_date on public.notifications (created_date desc);
create index if not exists idx_notifications_is_read on public.notifications (is_read);

create table if not exists public.password_resets (
  id bigint generated by default as identity primary key,
  email varchar(150) not null,
  token varchar(255) not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_password_resets_email on public.password_resets (email);
create index if not exists idx_password_resets_expires_at on public.password_resets (expires_at);

create table if not exists public.email_otp (
  otp_id bigint generated by default as identity primary key,
  email varchar(255) not null,
  otp_code varchar(6) not null,
  user_role text not null default 'admin' check (user_role in ('admin','handler','technician','faculty','student','pmo','dean','finance','guest')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now(),
  is_used boolean not null default false,
  attempts integer not null default 0
);

create index if not exists idx_email_otp_email on public.email_otp (email);
create index if not exists idx_email_otp_code on public.email_otp (otp_code);
create index if not exists idx_email_otp_expires_at on public.email_otp (expires_at);

create table if not exists public.user_sessions (
  session_id varchar(128) primary key,
  user_id varchar(32),
  user_role varchar(32),
  ip_address inet,
  user_agent text,
  last_activity timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  log_id bigint generated by default as identity primary key,
  user_id varchar(32),
  action varchar(100) not null,
  details text,
  ip_address inet,
  created_at timestamptz not null default now()
);

commit;
